[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "DEApython"
version = "0.1.0"
description = "Pipeline and Data Envelopment Analysis using public education data from Brazil"
authors = [{ name = "Pedro Silva", email = "silvapedro@outlook.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["basedosdados",
                "dealib",
                "dotenv",
                "google-cloud-storage",
                "numpy",
                "pandas",
                "pandera",
                "pyarrow",
                "PyYAML",
                "requests",
                "scipy",
                "tomlkit",
                "typing_extensions"]

[scripts]
deapipeline = "main:main"

[project.urls]
dashboard = "pbi link"
repository = "https://github.com/puffdapaz/DEApython"