[project]
name = "deapython"
version = "0.1.0"
description = "Python lakehouse pipeline replicating a Data Envelopment Analysis study on the efficiency of Brazilian municipalities in education spending, showcasing modern data engineering practices and analytics workflows"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "azure-core>=1.30.0",
    "azure-keyvault-secrets>=4.8.0",
    "azure-identity>=1.15.0",
    "basedosdados>=2.0.3",
    "cachetools>=7.0.5",
    "dealib>=1.0.0",
    "geobr>=0.2.2",
    "geopandas>=1.1.0",
    "google-cloud-storage>=3.9.0",
    "numpy>=1.26.4",
    "openmetadata-ingestion==1.11.*",
    "pandas>=2.3.3",
    "pandera>=0.29.0",
    "psycopg2-binary>=2.9",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "sqlalchemy>=1.4.0",
    "topojson>=1.10",
]
